### ISSUE TITLE
TODO for 4Pro

### ISSUE THREAD

**Issue by encryptize** [Encryptize/ngfw#1]
- [x] Remove Model Lock
- [x] DPC
- [x] Remove Speed Check
- [x] Remove Charging Mode
- [x] No KERS
- [x] Motor Start Speed
- [x] CRC
- [x] Shutdown Time
- [x] Cruise Control Delay
- [x] Region-Free
- [x] Pedestrian -> Eco Mode
- [ ] Static Brakelight
- [ ] Auto-Light
- [x] Pedestrian No-Blink
- [x] Current-Meter (not planned)
- [ ] Button Swap (not planned)
- [x] Custom KERS
- [x] Speed Limit for each mode
- [x] Nominal Current
- [x] Maximum Current
- [x] Minimum Brake Current
- [x] Maximum Brake Current
- [x] Wheel Size
- [x] Baudrate
- [x] Voltage Limit

**Comment by dnandha** [comment]
Good job @Encryptize !
If you need a simpler version of the "Static Brakelight" Mod, check the old version: https://github.com/dnandha/firmware-patcher/blob/d49ad0054488a9df1ded10a4f5a2c8a8646dcc2f/patcher.py#L194
It does not support "Auto-Light" though.

**Comment by encryptize** [comment]
> If you need a simpler version of the "Static Brakelight" Mod

@dnandha I have prepared a patch for the 4Pro, but I currently have no way to test it to see if it works properly. I don't have a controller with a working taillight, a common fault in this model. I will try this week to finish the remaining patches that do not require checking the tail light.
